name: 'gonzo_pit_strategy'
version: '1.0.0'
config-version: 2
profile: 'gonzo_pit_strategy'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]

models:
  gonzo_pit_strategy:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    features:
      +materialized: view
      +schema: features
    ml_prep:
      +materialized: table
      +schema: ml_prep
