version: 2

models:
  - name: stg_race_results
    description: Race session results with driver/team/circuit info
    columns:
      - name: round_id
        tests:
          - not_null
      - name: driver_id
        tests:
          - not_null
      - name: grid
        tests:
          - not_null
      - name: season_year
        tests:
          - not_null

  - name: stg_qualifying
    description: Qualifying times per round entry
    columns:
      - name: round_entry_id
        tests:
          - unique
          - not_null

  - name: stg_driver_standings
    description: Driver championship standings per round
    columns:
      - name: round_id
        tests:
          - not_null
      - name: driver_id
        tests:
          - not_null

  - name: stg_team_standings
    description: Team championship standings per round
    columns:
      - name: round_id
        tests:
          - not_null
      - name: team_id
        tests:
          - not_null
